
/CLEAR,NOSTART  ! Clear model since no SAVE found  


!---------------------------------------------------------------------------!
!-----------------------------Harmonic Analysis-----------------------------!
StarFreq=0               
FreqIncr=0.2      ! Frequeny Increment                                     
EndFreq=100.0

!---------------------------------------------------------------------------!
!---------------------------------------------------------------------------!
!room_off='Y2_2m'
!y_pick1=7.4
!y_pick2=7.6
x_pick1=8.75
y_pick1=4.8
x_pick2=8.75
y_pick2=4.8
!x_pick2=9
!y_pick2=6



!/INPUT,'fn_post\post_uni_Y_7pt5_TK','mac'


!DRtype = 'vary'   !select ths one for looping the damping ratio
DRtype = 'fix'	  !select ths one for constant damping ratio
!DRtype = 'testing'

!---------------------------------------------------------------------------!
!---------------------------------------------------------------------------! 



*IF,DRtype,EQ,'vary',THEN
	!Loop over DMPART from 0.1 to 1.0

	*do,iDR,1,5,1 

        !ftyp='PLATE'
        ftyp='FOOTING'


		*DIM,DR,ARRAY,1000,1
		*VREAD,DR(1,1),'ANSYS_DR_TEST2_X_SBAGM_V6_TR_DOE_1000','txt','fn_pre\RANDOM_INPUT\',jik,1,1000,1
		(1x,E14.7)
		*SET,D_bl, DR(iDR,1)
		
        *DIM,E_all,ARRAY,1000,1
		*VREAD,E_all(1,1),'ANSYS_E_TEST2_X_SBAGM_V6_TR_DOE_1000','txt','fn_pre\RANDOM_INPUT\',jik,1,1000,1
		(1x,E14.7)
		*SET,E_bl, E_all(iDR,1)

        /INPUT,'fn_pre\Pre_Para_slab_size_nonuni_TK','mac'
        /INPUT,'fn_fndtn_para\fndn_para_cnstvals_FULL','mac'

		!---------------------------------------------------------------------------!
		!---------------------------------------------------------------------------!
		!---------------------------------------------------------------------------!
        *IF,ftyp,EQ,'PLATE',THEN
            /INPUT,'fn_pre\Pre_BldMod_PlateFndtn_slabsize_nonuni_TK','mac' 
        *ELSEIF,ftyp,EQ,'FOOTING'
            /INPUT,'fn_pre\Pre_BldMod_FootingFndtn_slabsize_nonuni_TK','mac'
        *ENDIF
		!---------------------------------------------------------------------------!
		!---------------------------------------------------------------------------!
		!----------------------------Define Matrix27 -------------------------------!
        /INPUT,'fn_pre\Pre_CM_colbase_M27_TK','mac'		
        /INPUT,'fn_pre\Pre_M27_Full','mac'		

        !---------------------------Constraints for the LPM-------------------------!
        /INPUT,'fn_pre\Pre_Load_BCs','mac'			
		!/eof
		!---------------------------------------------------------------------------!
		!---------------------------------------------------------------------------!
		
		/INPUT,'fn_analysis\Analysis_TranFunc_VH','mac'

		/INPUT,'fn_post\post_uni_Y_7pt5_TK_VaryD','mac'
		/CLEAR
		PARRES
		
	*enddo
	
*ELSEIF,DRtype,EQ,'fix'	
    D_bl = 0.05

	!DR id number
    iDR = 1

    ftyp='FOOTING'
	E_bl = 30E9
	

	/INPUT,'fn_pre\Pre_Para_slab_size_nonuni_TK','mac'
    /INPUT,'fn_fndtn_para\fndn_para_cnstvals_FULL','mac'

    *IF,ftyp,EQ,'PLATE',THEN
        /INPUT,'fn_pre\Pre_BldMod_PlateFndtn_slabsize_nonuni_TK','mac' 
    *ELSEIF,ftyp,EQ,'FOOTING'
        /INPUT,'fn_pre\Pre_BldMod_FootingFndtn_slabsize_nonuni_TK','mac'
    *ENDIF

    /INPUT,'fn_pre\Pre_CM_colbase_M27_TK','mac'		
    /INPUT,'fn_pre\Pre_M27_Full','mac'		

    !---------------------------Constraints for the LPM-------------------------!
    /INPUT,'fn_pre\Pre_Load_BCs','mac'					
	/eof

	/INPUT,'fn_analysis\Analysis_TranFunc_VH','mac'

	/INPUT,'fn_post\post_uni_Y_7pt5_TK_VaryD','mac'	

*ELSEIF,DRtype,EQ,'testing'	
    D_bl = 0.05
    iDR = 2

    !ftyp='PLATE'
    ftyp='FOOTING'

    *DIM,E_all,ARRAY,1000,1
	*VREAD,E_all(1,1),'ANSYS_E_TEST2_X_SBAGM_V6_TR_DOE_1000','txt','fn_pre\RANDOM_INPUT\',jik,1,1000,1
	(1x,E14.7)
	*SET,E_bl, E_all(iDR,1)

    /INPUT,'fn_pre\Pre_Para_slab_size_nonuni_TK','mac'
    /INPUT,'fn_fndtn_para\fndn_para_cnstvals_FULL','mac'
	!---------------------------------------------------------------------------!
	!---------------------------------------------------------------------------!
	!---------------------------------------------------------------------------!
    *IF,ftyp,EQ,'PLATE',THEN
        /INPUT,'fn_pre\Pre_BldMod_PlateFndtn_slabsize_nonuni_TK','mac' 
    *ELSEIF,ftyp,EQ,'FOOTING'
        /INPUT,'fn_pre\Pre_BldMod_FootingFndtn_slabsize_nonuni_TK','mac'
    *ENDIF
	!---------------------------------------------------------------------------!
	!---------------------------------------------------------------------------!
	!----------------------------Define Matrix27 -------------------------------!
    /INPUT,'fn_pre\Pre_CM_colbase_M27_TK','mac'		
    /INPUT,'fn_pre\Pre_M27_Full','mac'		

    !---------------------------Constraints for the LPM-------------------------!
    /INPUT,'fn_pre\Pre_Load_BCs','mac'					
	!/eof
	!---------------------------------------------------------------------------!
	!---------------------------------------------------------------------------!
	
	/INPUT,'fn_analysis\Analysis_Harmonic_SuperP','mac'
    /INPUT,'fn_post\post_uni_Y_7pt5_TK_VaryD','mac'	

*ENDIF